-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#19120a',
  base01 = '#130d06',
  base02 = '#211a12',
  base03 = '#524434',
  base04 = '#d7c3ae',
  base05 = '#efe0d2',
  base06 = '#372f26',
  base07 = '#40382e',

  base08 = '#ffb4ab',
  base09 = '#bdd04f',
  base0A = '#ecbf86',
  base0B = '#ffb95a',
  base0C = '#9fb133',
  base0D = '#e59716',
  base0E = '#604014',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e59716',
  fg = '#19120a',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#1b2000',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#bdd04f',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#ecbf86',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#845400',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#130d06',
  fg = '#ffb95a',
})
