-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1b1206',
  base01 = '#150d03',
  base02 = '#241a0d',
  base03 = '#57432b',
  base04 = '#dec2a2',
  base05 = '#f3dfcb',
  base06 = '#3a2e21',
  base07 = '#433729',

  base08 = '#ffb4ab',
  base09 = '#f6bc70',
  base0A = '#ffb3ae',
  base0B = '#ffb3ae',
  base0C = '#643f00',
  base0D = '#7e2a29',
  base0E = '#733331',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#7e2a29',
  fg = '#1b1206',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffddb6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f6bc70',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#ffb3ae',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#9c413e',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#150d03',
  fg = '#ffb3ae',
})
